name: Build Android APK

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.4' # Or your preferred version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --flavor github


      - name: Sign APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks android/app/release.jks --ks-pass pass:trireme --key-pass pass:trireme --ks-key-alias release --v1-signing-enabled true --v2-signing-enabled true build/app/outputs/flutter-apk/app-github-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trireme-release-apk
          path: build/app/outputs/flutter-apk/app-github-release.apk
